[tool.poetry]
name = "crewai-playground"
version = "0.1.0"
description = ""
authors = ["Olaf <olaf@pobox.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
crewai = "^0.1.32"
python-dotenv = "^1.0.0"
duckduckgo-search = "^4.1.1"
openai = "^1.7.1"
unstructured = "^0.12.0"
pyowm = "^3.3.0"
tools = "^0.1.9"
wikipedia = "^1.4.0"
yfinance = "^0.2.35"
sec-api = "^1.0.17"
tiktoken = "^0.5.2"
faiss-cpu = "^1.7.4"
python-box = "^7.1.1"
langchain-mistralai = "^0.0.2"
langchain-community = "^0.0.12"
langchain-experimental = "^0.0.49"
e2b = "^0.13.15"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
