[tool.poetry]
name = "crewai-playground"
version = "0.1.0"
description = ""
authors = ["Olaf <olaf@pobox.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
crewai = "^0.1.24"
python-dotenv = "^1.0.0"
duckduckgo-search = "^4.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
