llm:
  anyscale:
    mistral:
      class: ChatOpenAI
      model: mistralai/Mistral-7B-Instruct-v0.1
      base_url: https://api.endpoints.anyscale.com/v1
      api_key: ANYSCALE_API_KEY
    mixtral:
      class: ChatOpenAI
      model: mistralai/Mixtral-8x7B-Instruct-v0.1
      base_url: https://api.endpoints.anyscale.com/v1
      api_key: ANYSCALE_API_KEY
  togetherai:
    mistral:
      class: ChatOpenAI
      model: mistralai/Mistral-7B-Instruct-v0.2
      base_url: https://api.together.xyz
      api_key: TOGETHERAI_API_KEY
  mistralai:
    mistral-medium:
      class: ChatOpenAI
      model: mistral-medium
      base_url: https://api.mistral.ai/v1
      api_key: MISTRALAI_API_KEY
  vertexai:
    gemini-pro:
      model: gemini-pro
      project: mygpt-383514
      location: us-central1 